#import "@local/mtgstory:0.1.0": conf
#show: doc => conf(
"Epic Experiment",
set_name: "Return to Ravnica",
author: "Jenna Helland",
doc)

#figure(image("011_Epic Experiment/02.jpg", width: 100%), caption: [Art by David Rapoza], supplement: none, numbering: none)

Trenz adjusted his Endotaxis-Goggles onto the bridge of his crooked nose. #emph[Good morning, Experiment Day] ! Blinking through the haze of Hyperocular Dust that wafted through the air, he sucked in a huge cone of it through his nostrils. Trenz enjoyed the scent of smoldering metal that wafted from the Magnetic Nitroxider, his mana-charged contraption that filled the entire east wall.

The early morning sun peeped through the cracked window, which overlooked the abandoned block of buildings that Trenz affectionately called the Empty Cup Row. He waved at the devoted klatch of Selesnya missionaries who had been picking away at the rubble—by hand—for months. At this rate, in 102.7 years, they’ll have cleared a nice spot to plant a new guild tree for their nascent community.

Trenz surveyed his drafty workshop and felt as if he must burst with pleasure. Somewhere, miles away in the Tenth District, the Firemind was probably reclining in his aerie in Nivix, considering a million things at once. Trenz wished he could hold a fraction of the things in his mind that Niv-Mizzet pondered in the blink of an eye.

Niv-Mizzet himself had bestowed this remote area of the city to Trenz as a playground for his Exospecial Experiments. Even before he was a full-fledged Chemister, Trenz had attracted the dragon’s attention when he created an Ætherprax tunnel from Nivix to the gates of Sunhome. Lately, the Firemind had been gifting Trenz with personal assignments that led him in directions that never would have occurred to him on his own. Yes, grand things were happening, and Trenz couldn’t remember that last time he’d slept. There was simply too much to do to bother shutting one’s eyes.

And today was Experiment Day! Trenz would crack the egg of truth and lay it at the claws of his master. Trenz strapped on his Omniblast helmet and lowered the Electrolocoscope over his face. He spun the scope around the room, marveling at incredible detail. There were a mason’s forgotten fingerprints along the vaulted ceiling. Yesterday’s bloodspots spattered across the toes of his reinforced boots. Trenz loved little details. It all added up to something grand.

Experimentation without risk would lead nowhere. An explosion was just the art of a mind on fire!

He strode across the warped floor boards and stood before the Magnetic Nitroxider, an element negotiator of his own design. So small. So perfect. If it were a pet mouse, he would kiss it between its fuzzy little ears. Trenz sighed with happiness. #emph[If this is thinking, I don’t know what I was doing before] , he thought happily.

His epic moment had arrived. He’d narrowed it down to four tests, each blossoming with potential. Each would yield gems of priceless information to deliver to the Aerie. But only one was the #emph[right]  choice. But which? Choose wisely, Mr. Trenz!

#v(0.35em)
#line(length: 100%, stroke: rgb(90%, 90%, 90%))
#v(0.35em)

#figure(image("011_Epic Experiment/04.jpg", width: 100%), caption: [Cyclonic Rift | Art by Chris Rahn], supplement: none, numbering: none)

Trenz selected the Aerial-Antistasis Chamber. He fired up the Mizzium coils and stepped into the Firemist field generated by the chamber. The mist eddied around him, stinging his cheeks with tiny barbs. Beneath his feet, the floor boards trembled. Outside, the sky darkened and the wind gusted dramatically. A violent funnel of wind materialized outside his workshop window, much to the horror of the Selesnya missionaries who rushed to take cover in a culvert.

The funnel tore through the abandoned block. It razed high-rise flats and demolished an empty Orzhov mission. Hordes of rubble-dwelling rats scurried for the drain as years of rubbish left by Gruul squatters swirled through the air. As quickly as it appeared, the funnel disappeared and the sun returned.

Trenz looked around his workshop in disappointment. A tornado of lightning-charged wind was not what he’d hoped for. Strangely, the Selesnyans were whooping outside his window. A large swath of the block was swept clear—as if a giant with a broom as taken sympathy on their mission. Joyful shouts of "The seed! Get the seed!" drifted through the air as Trenz went back to the drawing board.

#figure(image("011_Epic Experiment/06.jpg", width: 100%), caption: [Art by Scott M. Fischer], supplement: none, numbering: none)

Trenz selected the Spatial Ectofractalyzer. Ever so carefully, he poured the purest Ocular dust into the bolt hole. The dust began to glow faintly, which somehow made him sniffle. Inside the containment vial, the dust shuddered, clumped, and shuddered again. Trenz sneezed, and reality fragmented into beautiful shades of cobalt and puce. #emph[Oops] , Trenz thought. #emph[Too much dust] .

Meanwhile, deep in the bowels of the undercity, two shadowy figures were having a heated discussion. As soon as the puce light hit them, they stepped back into the shadows. A white-haired man appeared out of nowhere, cursed loudly, and began stomping noisily up the cobblestones toward the surface. As he disappeared from sight, the startled pair looked at each other in amazement. A beautiful portal shimmered in front of them, and Mr. Taz was sure it would take them exactly where they needed to go.

"Well, Krenko," Taz murmured to the hook-nosed goblin standing beside him. "Getting into the Orzhov inner sanctum might not be as difficult as you initially believed."

#figure(image("011_Epic Experiment/08.jpg", width: 100%), caption: [Mizzium Mortars | Art by Christina Davis], supplement: none, numbering: none)

Trenz selected the Megathermal Geolometer. Keeping his head #emph[way]  back, he tapped the geolometer against the supercharged Mizzium coils. Nothing happened. He blew off the dust bunnies and tapped it harder.

Suddenly, spires of molten flame rocketed through the air. Super-heated metal fragments rained down over the district and tore coin-sized holes in roofs for miles around. The sizzle of burning metal gave way to slow-rolling earthquakes that made the streets undulate like waves.

The bright lights and thunderous racket attracted the attention of the Rakdos cultists. Nothing says "celebration" quite like widespread, random destruction. Bloodwitches stumbled out of Rix Maadi. Pleasure clubs emptied all over the city. The roustabouts and spikers roused their reluctant neighbors and soon the streets filled with merrymakers.

Amid their frolicking, the cultists agreed they should do this #emph[every]  year, and thus the new Festival of Fire-Rain Bloodletting Mayhem Neighbor Appreciation Day was born.

The show continued long into the night—even after Trenz threw the Geolometer out the window and went to bed.

#figure(image("011_Epic Experiment/10.jpg", width: 100%), caption: [Epic Experiment | Art by Dan Scott], supplement: none, numbering: none)

Trenz choose the Neural Schisatrode. He tightened the screws against his temples and waited expectantly. There was a jangle followed by a frightened squeak. Air rushed in through his ears like his brain had turned into a Suctionatronic device. His thoughts seem to pulverize under the weight of some mental hammer. "No!" he cried. "I must not let the Firemind down." Desperately, he raised his Zygon Cuff and, suddenly, the room erupted in lightning and pure, unadulterated genius. He had chosen correctly, and the reward was in his electrified grasp at last!

