#import "@local/mtgset:0.1.0": conf
#show: doc => conf("March of the Machine", doc)

#include "./051 - March of the Machine/001_Episode 1: Triumph of the Fleshless.typ"
#include "./051 - March of the Machine/002_Episode 2: Holding Your Breath.typ"
#include "./051 - March of the Machine/003_Episode 3: Mother, Son, and Story.typ"
#include "./051 - March of the Machine/004_Episode 4: Beneath Eyes Unblinking.typ"
#include "./051 - March of the Machine/005_Arcavios: A Radiant Heart.typ"
#include "./051 - March of the Machine/006_Ikoria: Survival of the Fittest.typ"
#include "./051 - March of the Machine/007_Episode 5: Cathartic Reunion.typ"
#include "./051 - March of the Machine/008_Ixalan: Three Hundred Steps under the Sun.typ"
#include "./051 - March of the Machine/009_Innistrad: Family Game Night.typ"
#include "./051 - March of the Machine/010_Eldraine: The Adventures of Rankle, Master of Love.typ"
#include "./051 - March of the Machine/011_Episode 6: The Last to Leave.typ"
#include "./051 - March of the Machine/012_Episode 7: Divine Intervention.typ"
#include "./051 - March of the Machine/013_Episode 8: Wrenn and Eight.typ"
#include "./051 - March of the Machine/014_Ravnica: One and the Same.typ"
#include "./051 - March of the Machine/015_New Capenna: The Fall of Park Heights.typ"
#include "./051 - March of the Machine/016_Zendikar: Battles in the Field and in the Mind.typ"
#include "./051 - March of the Machine/017_Episode 9: The Old Sins of New Phyrexia.typ"
#include "./051 - March of the Machine/018_Episode 10: The Rhythms of Life.typ"
